2023-09-02 07:26:29,606 INFO    StreamThr :8735 [internal.py:wandb_internal():86] W&B internal server running at pid: 8735, started at: 2023-09-02 07:26:29.605560
2023-09-02 07:26:29,607 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status
2023-09-02 07:26:29,610 INFO    WriterThread:8735 [datastore.py:open_for_write():85] open: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/run-ctrk7pd3.wandb
2023-09-02 07:26:29,611 DEBUG   SenderThread:8735 [sender.py:send():375] send: header
2023-09-02 07:26:30,787 DEBUG   SenderThread:8735 [sender.py:send():375] send: run
2023-09-02 07:26:31,821 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: check_version
2023-09-02 07:26:31,822 INFO    SenderThread:8735 [dir_watcher.py:__init__():219] watching files in: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files
2023-09-02 07:26:31,823 INFO    SenderThread:8735 [sender.py:_start_run_threads():1124] run started: ctrk7pd3 with start time 1693610789.606064
2023-09-02 07:26:31,823 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: summary_record
2023-09-02 07:26:31,823 INFO    SenderThread:8735 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-09-02 07:26:31,823 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: check_version
2023-09-02 07:26:31,933 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: run_start
2023-09-02 07:26:31,942 DEBUG   HandlerThread:8735 [system_info.py:__init__():31] System info init
2023-09-02 07:26:31,942 DEBUG   HandlerThread:8735 [system_info.py:__init__():46] System info init done
2023-09-02 07:26:31,942 INFO    HandlerThread:8735 [system_monitor.py:start():181] Starting system monitor
2023-09-02 07:26:31,943 INFO    SystemMonitor:8735 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-02 07:26:31,943 INFO    HandlerThread:8735 [system_monitor.py:probe():201] Collecting system info
2023-09-02 07:26:31,944 INFO    SystemMonitor:8735 [interfaces.py:start():190] Started cpu monitoring
2023-09-02 07:26:31,945 INFO    SystemMonitor:8735 [interfaces.py:start():190] Started disk monitoring
2023-09-02 07:26:31,945 INFO    SystemMonitor:8735 [interfaces.py:start():190] Started gpu monitoring
2023-09-02 07:26:31,946 INFO    SystemMonitor:8735 [interfaces.py:start():190] Started memory monitoring
2023-09-02 07:26:31,947 INFO    SystemMonitor:8735 [interfaces.py:start():190] Started network monitoring
2023-09-02 07:26:31,959 DEBUG   HandlerThread:8735 [system_info.py:probe():195] Probing system
2023-09-02 07:26:31,966 DEBUG   HandlerThread:8735 [system_info.py:_probe_git():180] Probing git
2023-09-02 07:26:31,979 DEBUG   HandlerThread:8735 [system_info.py:_probe_git():188] Probing git done
2023-09-02 07:26:31,979 DEBUG   HandlerThread:8735 [system_info.py:probe():240] Probing system done
2023-09-02 07:26:31,979 DEBUG   HandlerThread:8735 [system_monitor.py:probe():210] {'os': 'Linux-5.4.0-99-generic-x86_64-with-glibc2.17', 'python': '3.8.10', 'heartbeatAt': '2023-09-01T23:26:31.959796', 'startedAt': '2023-09-01T23:26:29.598286', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/llama_2_trlx.py', 'codePath': 'Train/SVAMP/llama_2_trlx.py', 'git': {'remote': 'https://github.com/Greenoso/llm_thought.git', 'commit': '24305a3a985102cd18f50a6e8694b77e36025f3a'}, 'email': 'jiacheng.liu.19.ucl@gmail.com', 'root': '/root/autodl-tmp/msc_ml/llm_thought', 'host': 'autodl-container-55da118bfa-7e0e117f', 'username': 'root', 'executable': '/root/miniconda3/bin/python', 'cpu_count': 40, 'cpu_count_logical': 80, 'cpu_freq': {'current': 2999.864000000001, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}], 'disk': {'total': 30.0, 'used': 12.480262756347656}, 'gpu': 'Tesla V100S-PCIE-32GB', 'gpu_count': 2, 'gpu_devices': [{'name': 'Tesla V100S-PCIE-32GB', 'memory_total': 34359738368}, {'name': 'Tesla V100S-PCIE-32GB', 'memory_total': 34359738368}], 'memory': {'total': 629.8885612487793}}
2023-09-02 07:26:31,980 INFO    HandlerThread:8735 [system_monitor.py:probe():211] Finished collecting system info
2023-09-02 07:26:31,980 INFO    HandlerThread:8735 [system_monitor.py:probe():214] Publishing system info
2023-09-02 07:26:31,980 DEBUG   HandlerThread:8735 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-09-02 07:26:31,980 DEBUG   HandlerThread:8735 [system_info.py:_save_pip():67] Saving pip packages done
2023-09-02 07:26:31,980 DEBUG   HandlerThread:8735 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-09-02 07:26:32,824 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/requirements.txt
2023-09-02 07:26:32,825 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/wandb-summary.json
2023-09-02 07:26:32,825 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/conda-environment.yaml
2023-09-02 07:26:35,481 DEBUG   HandlerThread:8735 [system_info.py:_save_conda():86] Saving conda packages done
2023-09-02 07:26:35,482 INFO    HandlerThread:8735 [system_monitor.py:probe():216] Finished publishing system info
2023-09-02 07:26:35,489 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:26:35,490 DEBUG   SenderThread:8735 [sender.py:send():375] send: files
2023-09-02 07:26:35,490 INFO    SenderThread:8735 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-09-02 07:26:35,496 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 07:26:35,496 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: stop_status
2023-09-02 07:26:35,826 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/conda-environment.yaml
2023-09-02 07:26:35,827 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/wandb-metadata.json
2023-09-02 07:26:35,886 DEBUG   SenderThread:8735 [sender.py:send():375] send: telemetry
2023-09-02 07:26:35,887 DEBUG   SenderThread:8735 [sender.py:send():375] send: config
2023-09-02 07:26:35,939 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:26:35,939 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:26:35,939 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:26:36,827 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:26:37,285 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:26:37,285 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:26:37,285 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:26:38,828 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:26:39,995 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:26:39,995 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:26:39,995 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:26:39,995 INFO    wandb-upload_0:8735 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-02 07:26:40,891 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:26:44,531 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:26:44,531 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:26:44,531 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:26:46,110 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:26:46,830 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:26:47,831 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:26:50,496 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 07:26:50,497 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: stop_status
2023-09-02 07:26:51,784 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:26:54,754 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:26:54,755 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:26:54,755 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:26:56,786 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:01,791 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:02,836 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/config.yaml
2023-09-02 07:27:05,497 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 07:27:05,497 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: stop_status
2023-09-02 07:27:07,823 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:12,824 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:14,288 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:27:14,288 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:27:14,288 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:27:17,825 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:20,497 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 07:27:20,498 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: stop_status
2023-09-02 07:27:23,762 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:28,763 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:31,948 DEBUG   SystemMonitor:8735 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-02 07:27:31,949 DEBUG   SenderThread:8735 [sender.py:send():375] send: stats
2023-09-02 07:27:33,950 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:35,497 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 07:27:35,498 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: stop_status
2023-09-02 07:27:38,847 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:27:39,407 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:43,849 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:27:44,920 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:47,002 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:27:47,002 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:27:47,002 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:27:49,921 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:50,497 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 07:27:50,498 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: stop_status
2023-09-02 07:27:55,768 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:58,010 DEBUG   SenderThread:8735 [sender.py:send():375] send: exit
2023-09-02 07:27:58,011 INFO    SenderThread:8735 [sender.py:send_exit():598] handling exit code: 255
2023-09-02 07:27:58,011 INFO    SenderThread:8735 [sender.py:send_exit():600] handling runtime: 86
2023-09-02 07:27:58,013 INFO    SenderThread:8735 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-09-02 07:27:58,013 INFO    SenderThread:8735 [sender.py:send_exit():606] send defer
2023-09-02 07:27:58,013 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,013 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-02 07:27:58,013 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,014 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 0
2023-09-02 07:27:58,014 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 1
2023-09-02 07:27:58,014 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,014 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-02 07:27:58,014 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,014 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 1
2023-09-02 07:27:58,014 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 2
2023-09-02 07:27:58,014 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,014 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-02 07:27:58,014 INFO    HandlerThread:8735 [system_monitor.py:finish():190] Stopping system monitor
2023-09-02 07:27:58,015 DEBUG   SystemMonitor:8735 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-02 07:27:58,015 DEBUG   SystemMonitor:8735 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-02 07:27:58,016 INFO    HandlerThread:8735 [interfaces.py:finish():202] Joined cpu monitor
2023-09-02 07:27:58,016 INFO    HandlerThread:8735 [interfaces.py:finish():202] Joined disk monitor
2023-09-02 07:27:58,032 INFO    HandlerThread:8735 [interfaces.py:finish():202] Joined gpu monitor
2023-09-02 07:27:58,032 INFO    HandlerThread:8735 [interfaces.py:finish():202] Joined memory monitor
2023-09-02 07:27:58,032 INFO    HandlerThread:8735 [interfaces.py:finish():202] Joined network monitor
2023-09-02 07:27:58,033 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,033 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 2
2023-09-02 07:27:58,033 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 3
2023-09-02 07:27:58,033 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,033 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-02 07:27:58,033 DEBUG   SenderThread:8735 [sender.py:send():375] send: stats
2023-09-02 07:27:58,034 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,034 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 3
2023-09-02 07:27:58,034 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 4
2023-09-02 07:27:58,034 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,034 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-02 07:27:58,035 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,035 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 4
2023-09-02 07:27:58,035 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 5
2023-09-02 07:27:58,035 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,035 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-02 07:27:58,035 DEBUG   SenderThread:8735 [sender.py:send():375] send: summary
2023-09-02 07:27:58,035 INFO    SenderThread:8735 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-09-02 07:27:58,036 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,036 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 5
2023-09-02 07:27:58,036 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 6
2023-09-02 07:27:58,036 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,036 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-02 07:27:58,036 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,036 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 6
2023-09-02 07:27:58,036 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 7
2023-09-02 07:27:58,036 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 07:27:58,037 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:27:58,037 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-02 07:27:58,037 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:27:58,037 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 7
2023-09-02 07:27:58,855 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/wandb-summary.json
2023-09-02 07:27:59,011 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-02 07:27:59,856 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:28:01,207 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 8
2023-09-02 07:28:01,208 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: poll_exit
2023-09-02 07:28:01,208 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:28:01,208 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-02 07:28:01,209 DEBUG   SenderThread:8735 [sender.py:send_request():402] send_request: defer
2023-09-02 07:28:01,209 INFO    SenderThread:8735 [sender.py:send_request_defer():622] handle sender defer: 8
2023-09-02 07:28:01,216 INFO    SenderThread:8735 [sender.py:transition_state():626] send defer: 9
2023-09-02 07:28:01,217 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: defer
2023-09-02 07:28:01,217 INFO    HandlerThread:8735 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-02 07:28:01,217 DEBUG   SenderThread:8735 [sender.py:send():375] send: artifact
2023-09-02 07:28:01,857 INFO    Thread-12 :8735 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/files/output.log
2023-09-02 07:28:02,664 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:02,664 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:28:02,665 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:02,894 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:02,894 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:28:02,894 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:03,990 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:03,990 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:28:03,990 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:03,990 INFO    wandb-upload_1:8735 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-02 07:28:04,010 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:04,010 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:28:04,010 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:04,010 INFO    wandb-upload_2:8735 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-02 07:28:04,012 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 07:28:06,193 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:06,193 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:28:06,193 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:06,410 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:06,410 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:28:06,410 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:09,014 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 07:28:10,821 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:10,821 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:28:10,821 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:11,222 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:11,223 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:28:11,223 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:14,016 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 07:28:19,018 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 07:28:19,313 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:19,313 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:28:19,314 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:20,151 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:20,151 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:28:20,152 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:24,020 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 07:28:29,022 DEBUG   HandlerThread:8735 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 07:28:30,733 WARNING StreamThr :8735 [internal.py:is_dead():414] Internal process exiting, parent pid 8634 disappeared
2023-09-02 07:28:30,733 ERROR   StreamThr :8735 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-02 07:28:31,022 INFO    HandlerThread:8735 [handler.py:finish():845] shutting down handler
2023-09-02 07:28:31,223 INFO    WriterThread:8735 [datastore.py:close():298] close: /root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/wandb/run-20230902_072629-ctrk7pd3/run-ctrk7pd3.wandb
2023-09-02 07:28:37,177 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:37,177 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:28:37,177 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:28:37,473 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:28:37,473 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:28:37,473 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:29:07,087 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:29:07,087 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:29:07,087 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:29:11,350 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:29:11,351 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:29:11,351 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:29:13,817 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:29:13,817 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:29:13,817 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:30:20,283 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:30:20,283 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:30:20,283 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:30:31,879 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:30:31,879 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:30:31,879 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:31:32,337 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:31:32,337 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:31:32,337 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:32:35,030 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:32:35,030 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:32:35,031 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:33:02,026 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:33:02,026 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:33:02,027 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:36:01,978 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:36:01,978 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:36:01,978 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:37:24,946 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:37:24,947 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:37:24,947 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:37:27,127 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:37:27,127 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:37:27,127 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:41:39,580 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:41:39,580 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:41:39,580 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:43:04,902 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:43:04,902 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:43:04,902 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:43:12,686 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:43:12,686 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:43:12,686 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:46:54,252 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:46:54,252 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:46:54,252 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:48:32,839 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:48:32,840 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:48:32,840 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:49:04,524 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:49:04,524 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:49:04,524 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:53:02,740 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:53:02,740 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:53:02,741 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:54:24,215 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:54:24,215 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 07:54:24,216 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:54:56,315 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:54:56,315 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 07:54:56,315 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 07:58:42,327 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 07:58:42,328 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 07:58:42,328 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:00:11,139 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:00:11,139 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 08:00:11,140 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:00:32,297 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:00:32,298 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 08:00:32,298 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:03:45,256 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:03:45,257 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 08:03:45,257 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:05:31,494 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:05:31,494 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 08:05:31,494 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:06:21,545 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:06:21,545 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 08:06:21,545 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:09:26,889 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:09:26,889 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 08:09:26,889 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:11:04,351 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:11:04,351 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 08:11:04,351 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:12:24,845 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:12:24,846 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 08:12:24,846 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:15:14,320 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:15:14,320 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 08:15:14,320 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:16:12,148 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:16:12,149 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 08:16:12,149 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:17:51,052 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:17:51,053 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 08:17:51,053 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:20:38,314 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:20:38,314 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 08:20:38,314 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:22:03,523 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:22:03,523 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 08:22:03,523 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:23:10,347 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:23:10,347 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 08:23:10,347 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:26:33,373 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/ctrk7pd3/wandb-metadata.json?Expires=1693697195&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FuM%2BeHm%2BDSOhpfEoJmwnD2LlMOAHAb8BkwCdlIdhY%2Bx5m%2Bi4rMMLKftuaxAeQUo2qQd87Lq8tt8gKVwKUq6DZdIbOPKxeF2pGjn2vU8zdkDZAzrcx0mw3bumiEr6zp3VHFxbyhaeGi3q4LQ4N5xikXViTk8SDamWOFTVe2DqkjOUHVgN%2BojPkeS%2FyfrVBaV9aEiKXZYbGggIO%2BzVpvJhsHa7BOwf%2F86jNQRr519H6URppMDnBgR5k1C%2FagZ%2BLA%2B1dzOJMvcwlDbCWC9EuEm0zTfquvalsOH%2BpKclmVvIxWAXnzcEUY7GMJYKk3jJTZV0vVPAk5hGoxntuS7%2FxmDQNw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:26:33,373 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 08:26:33,373 ERROR   wandb-upload_0:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:27:20,845 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/7cb72c6070c7b17c860e614316150974?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DFORcDovIOKH37gs9zZB0wbqs1qAmxO0gaTPRoO4gbbvCcc9z8sglluMY0DiZgg8nLioDlIz0DTxhk6dRr3gFaAreO%2FuqbdECpfsJVAhcSQ36VIAKkDqCjEjd9b6lJ%2BDg2kODB2uOTyYBXv2vagxe89beNZa3PKOg2YWqzY3X7zIogs33hqmE9WmOoinMDm3urSdI%2FF2%2BfDRZ%2FMFscG1DVD1rx3%2FYW%2FUPjBsQCRlSx7tQGgweTXhpDpZ3OtuupWwVooxuXeM%2B%2ByTN2HTI0u2nbM2hAKLISR8sHZYI8jVln3gYXDjZMwIHokMwdO42h4s7k2CJH1fVPOKF8yrLK4B2A%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:27:20,845 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fLcsYHDHsXyGDmFDFhUJdA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '4296'}
2023-09-02 08:27:20,845 ERROR   wandb-upload_1:8735 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 08:28:19,788 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557265222/1ec1ec99cc2cec712cbadad9d007c182?Expires=1693697282&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KHB7CFLo5o5K74z7CqSe988%2BFUEyRqsd9rwaVDtpWj5UKY1IaeWHABiSwhxvYX0j2cRgxQor3v%2B4YeoE54daUSPiqiBudK%2BPHcOKU29yBBcNw9Y6OXKErnpLYcEaPmYvIFA9UGlOgyzHRFdHPDeJlWtCMoSGVrElLeWSMbBRr0fCty8FcVgTVmRrYPRoROXnZABDLSpNJraqxth9hf69OuqOpORyvzT1cPN8Ew1DRmdVS2rzto%2FWrswHPUBmbJdAWhUIjlvUmJ%2BrNtinPT4LjSU5sOul%2FMHDnsEx3K2CNowVkfYaAQJnwIP2hsKV%2FztkHFidcWostt9zZTS2G1nhxg%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 08:28:19,788 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'HsHsmcws7HEsutrZ0AfBgg==', 'Content-Type': 'application/json', 'Content-Length': '12677'}
2023-09-02 08:28:19,788 ERROR   wandb-upload_2:8735 [internal_api.py:upload_file():2103] upload_file response body: 
