2023-09-02 20:03:25,635 INFO    StreamThr :3390 [internal.py:wandb_internal():86] W&B internal server running at pid: 3390, started at: 2023-09-02 20:03:25.634830
2023-09-02 20:03:25,639 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status
2023-09-02 20:03:25,641 INFO    WriterThread:3390 [datastore.py:open_for_write():85] open: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/run-vwk90r2y.wandb
2023-09-02 20:03:25,642 DEBUG   SenderThread:3390 [sender.py:send():375] send: header
2023-09-02 20:03:27,003 DEBUG   SenderThread:3390 [sender.py:send():375] send: run
2023-09-02 20:03:27,805 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: check_version
2023-09-02 20:03:27,807 INFO    SenderThread:3390 [dir_watcher.py:__init__():219] watching files in: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files
2023-09-02 20:03:27,807 INFO    SenderThread:3390 [sender.py:_start_run_threads():1124] run started: vwk90r2y with start time 1693656205.635003
2023-09-02 20:03:27,807 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: summary_record
2023-09-02 20:03:27,807 INFO    SenderThread:3390 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-09-02 20:03:27,808 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: check_version
2023-09-02 20:03:27,919 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: run_start
2023-09-02 20:03:27,931 DEBUG   HandlerThread:3390 [system_info.py:__init__():31] System info init
2023-09-02 20:03:27,932 DEBUG   HandlerThread:3390 [system_info.py:__init__():46] System info init done
2023-09-02 20:03:27,932 INFO    HandlerThread:3390 [system_monitor.py:start():181] Starting system monitor
2023-09-02 20:03:27,932 INFO    SystemMonitor:3390 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-02 20:03:27,933 INFO    HandlerThread:3390 [system_monitor.py:probe():201] Collecting system info
2023-09-02 20:03:27,934 INFO    SystemMonitor:3390 [interfaces.py:start():190] Started cpu monitoring
2023-09-02 20:03:27,935 INFO    SystemMonitor:3390 [interfaces.py:start():190] Started disk monitoring
2023-09-02 20:03:27,935 INFO    SystemMonitor:3390 [interfaces.py:start():190] Started gpu monitoring
2023-09-02 20:03:27,936 INFO    SystemMonitor:3390 [interfaces.py:start():190] Started memory monitoring
2023-09-02 20:03:27,936 INFO    SystemMonitor:3390 [interfaces.py:start():190] Started network monitoring
2023-09-02 20:03:27,970 DEBUG   HandlerThread:3390 [system_info.py:probe():195] Probing system
2023-09-02 20:03:27,978 DEBUG   HandlerThread:3390 [system_info.py:_probe_git():180] Probing git
2023-09-02 20:03:27,994 DEBUG   HandlerThread:3390 [system_info.py:_probe_git():188] Probing git done
2023-09-02 20:03:27,994 DEBUG   HandlerThread:3390 [system_info.py:probe():240] Probing system done
2023-09-02 20:03:27,995 DEBUG   HandlerThread:3390 [system_monitor.py:probe():210] {'os': 'Linux-5.4.0-99-generic-x86_64-with-glibc2.17', 'python': '3.8.10', 'heartbeatAt': '2023-09-02T12:03:27.970684', 'startedAt': '2023-09-02T12:03:25.625231', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/root/autodl-tmp/msc_ml/llm_thought/Train/SVAMP/llama_2_trlx.py', 'codePath': 'Train/SVAMP/llama_2_trlx.py', 'git': {'remote': 'https://github.com/Greenoso/llm_thought.git', 'commit': '24305a3a985102cd18f50a6e8694b77e36025f3a'}, 'email': 'jiacheng.liu.19.ucl@gmail.com', 'root': '/root/autodl-tmp/msc_ml/llm_thought', 'host': 'autodl-container-55da118bfa-7e0e117f', 'username': 'root', 'executable': '/root/miniconda3/bin/python', 'cpu_count': 40, 'cpu_count_logical': 80, 'cpu_freq': {'current': 2999.864000000001, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}, {'current': 2999.864, 'min': 0.0, 'max': 0.0}], 'disk': {'total': 30.0, 'used': 12.480709075927734}, 'gpu': 'Tesla V100S-PCIE-32GB', 'gpu_count': 2, 'gpu_devices': [{'name': 'Tesla V100S-PCIE-32GB', 'memory_total': 34359738368}, {'name': 'Tesla V100S-PCIE-32GB', 'memory_total': 34359738368}], 'memory': {'total': 629.8885612487793}}
2023-09-02 20:03:27,995 INFO    HandlerThread:3390 [system_monitor.py:probe():211] Finished collecting system info
2023-09-02 20:03:27,995 INFO    HandlerThread:3390 [system_monitor.py:probe():214] Publishing system info
2023-09-02 20:03:27,995 DEBUG   HandlerThread:3390 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-09-02 20:03:27,995 DEBUG   HandlerThread:3390 [system_info.py:_save_pip():67] Saving pip packages done
2023-09-02 20:03:27,996 DEBUG   HandlerThread:3390 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-09-02 20:03:28,809 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/wandb-summary.json
2023-09-02 20:03:28,809 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/requirements.txt
2023-09-02 20:03:28,809 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/conda-environment.yaml
2023-09-02 20:03:31,501 DEBUG   HandlerThread:3390 [system_info.py:_save_conda():86] Saving conda packages done
2023-09-02 20:03:31,502 INFO    HandlerThread:3390 [system_monitor.py:probe():216] Finished publishing system info
2023-09-02 20:03:31,510 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:03:31,511 DEBUG   SenderThread:3390 [sender.py:send():375] send: files
2023-09-02 20:03:31,511 INFO    SenderThread:3390 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-09-02 20:03:31,520 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:03:31,520 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:03:31,808 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/conda-environment.yaml
2023-09-02 20:03:31,809 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/wandb-metadata.json
2023-09-02 20:03:31,887 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:03:31,887 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:03:31,887 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:03:31,943 DEBUG   SenderThread:3390 [sender.py:send():375] send: telemetry
2023-09-02 20:03:31,944 DEBUG   SenderThread:3390 [sender.py:send():375] send: config
2023-09-02 20:03:32,809 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_created():278] file/dir created: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:03:33,359 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:03:33,359 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:03:33,359 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:03:34,811 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:03:35,565 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:03:35,566 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:03:35,566 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:03:35,566 INFO    wandb-upload_0:3390 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-02 20:03:35,947 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:03:40,644 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:03:40,644 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:03:40,644 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:03:40,948 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:03:45,949 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:03:46,521 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:03:46,523 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:03:48,818 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:03:49,968 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:03:49,968 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:03:49,968 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:03:50,819 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:03:51,236 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:03:56,242 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:03:56,822 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/config.yaml
2023-09-02 20:04:01,521 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:04:01,523 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:04:01,751 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:06,753 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:06,932 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:04:06,932 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:04:06,932 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:04:11,754 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:16,521 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:04:16,522 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:04:16,777 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:21,778 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:26,779 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:27,937 DEBUG   SystemMonitor:3390 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-02 20:04:27,939 DEBUG   SenderThread:3390 [sender.py:send():375] send: stats
2023-09-02 20:04:31,522 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:04:31,522 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:04:31,812 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:36,813 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:42,448 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:04:42,448 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:04:42,448 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:04:42,666 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:42,839 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:04:44,298 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: partial_history
2023-09-02 20:04:46,523 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:04:46,524 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:04:46,841 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:04:47,791 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:52,792 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:57,794 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:04:57,941 DEBUG   SenderThread:3390 [sender.py:send():375] send: stats
2023-09-02 20:05:01,523 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:05:01,524 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:05:03,766 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:08,768 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:13,769 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:16,523 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:05:16,524 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:05:18,832 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:23,833 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:27,942 DEBUG   SenderThread:3390 [sender.py:send():375] send: stats
2023-09-02 20:05:28,943 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:31,523 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:05:31,524 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:05:32,859 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:05:34,758 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:39,759 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:44,761 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:46,524 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: stop_status
2023-09-02 20:05:46,524 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: stop_status
2023-09-02 20:05:49,801 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:54,802 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:05:55,827 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:05:55,827 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:05:55,827 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:05:57,943 DEBUG   SenderThread:3390 [sender.py:send():375] send: stats
2023-09-02 20:05:59,945 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:06:00,940 DEBUG   SenderThread:3390 [sender.py:send():375] send: exit
2023-09-02 20:06:00,940 INFO    SenderThread:3390 [sender.py:send_exit():598] handling exit code: 0
2023-09-02 20:06:00,940 INFO    SenderThread:3390 [sender.py:send_exit():600] handling runtime: 153
2023-09-02 20:06:00,941 INFO    SenderThread:3390 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-09-02 20:06:00,941 INFO    SenderThread:3390 [sender.py:send_exit():606] send defer
2023-09-02 20:06:00,941 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,942 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-02 20:06:00,942 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,942 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 0
2023-09-02 20:06:00,942 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 1
2023-09-02 20:06:00,942 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,942 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-02 20:06:00,943 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,943 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 1
2023-09-02 20:06:00,943 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 2
2023-09-02 20:06:00,943 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,943 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-02 20:06:00,943 INFO    HandlerThread:3390 [system_monitor.py:finish():190] Stopping system monitor
2023-09-02 20:06:00,944 DEBUG   SystemMonitor:3390 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-02 20:06:00,944 DEBUG   SystemMonitor:3390 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-02 20:06:00,945 INFO    HandlerThread:3390 [interfaces.py:finish():202] Joined cpu monitor
2023-09-02 20:06:00,946 INFO    HandlerThread:3390 [interfaces.py:finish():202] Joined disk monitor
2023-09-02 20:06:00,957 INFO    HandlerThread:3390 [interfaces.py:finish():202] Joined gpu monitor
2023-09-02 20:06:00,958 INFO    HandlerThread:3390 [interfaces.py:finish():202] Joined memory monitor
2023-09-02 20:06:00,958 INFO    HandlerThread:3390 [interfaces.py:finish():202] Joined network monitor
2023-09-02 20:06:00,958 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,959 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 2
2023-09-02 20:06:00,959 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 3
2023-09-02 20:06:00,959 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,959 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-02 20:06:00,960 DEBUG   SenderThread:3390 [sender.py:send():375] send: stats
2023-09-02 20:06:00,961 DEBUG   SenderThread:3390 [sender.py:send():375] send: history
2023-09-02 20:06:00,962 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: summary_record
2023-09-02 20:06:00,962 INFO    SenderThread:3390 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-09-02 20:06:00,962 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,962 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 3
2023-09-02 20:06:00,962 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 4
2023-09-02 20:06:00,963 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,963 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-02 20:06:00,963 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,963 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 4
2023-09-02 20:06:00,963 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 5
2023-09-02 20:06:00,963 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,963 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-02 20:06:00,964 DEBUG   SenderThread:3390 [sender.py:send():375] send: summary
2023-09-02 20:06:00,964 INFO    SenderThread:3390 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-09-02 20:06:00,964 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,964 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 5
2023-09-02 20:06:00,964 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 6
2023-09-02 20:06:00,964 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,965 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-02 20:06:00,965 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,965 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 6
2023-09-02 20:06:00,965 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 7
2023-09-02 20:06:00,965 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: status_report
2023-09-02 20:06:00,965 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:00,965 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-02 20:06:00,966 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:00,966 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 7
2023-09-02 20:06:01,870 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/wandb-summary.json
2023-09-02 20:06:01,937 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-02 20:06:02,435 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 8
2023-09-02 20:06:02,435 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: poll_exit
2023-09-02 20:06:02,436 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:02,436 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-02 20:06:02,437 DEBUG   SenderThread:3390 [sender.py:send_request():402] send_request: defer
2023-09-02 20:06:02,437 INFO    SenderThread:3390 [sender.py:send_request_defer():622] handle sender defer: 8
2023-09-02 20:06:02,446 INFO    SenderThread:3390 [sender.py:transition_state():626] send defer: 9
2023-09-02 20:06:02,446 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: defer
2023-09-02 20:06:02,446 INFO    HandlerThread:3390 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-02 20:06:02,447 DEBUG   SenderThread:3390 [sender.py:send():375] send: artifact
2023-09-02 20:06:02,870 INFO    Thread-12 :3390 [dir_watcher.py:_on_file_modified():295] file/dir modified: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/files/output.log
2023-09-02 20:06:02,938 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-02 20:06:04,277 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:06:04,277 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:06:04,277 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:06:05,145 INFO    wandb-upload_1:3390 [upload_job.py:push():95] Uploaded file /root/.local/share/wandb/artifacts/staging/tmpcqa_4uwq
2023-09-02 20:06:05,691 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:06:05,692 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:06:05,692 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:06:07,791 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:06:07,791 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:06:07,791 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:06:07,791 INFO    wandb-upload_2:3390 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-02 20:06:07,941 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 20:06:12,740 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:06:12,740 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:06:12,740 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:06:12,944 DEBUG   HandlerThread:3390 [handler.py:handle_request():144] handle_request: keepalive
2023-09-02 20:06:14,820 WARNING StreamThr :3390 [internal.py:is_dead():414] Internal process exiting, parent pid 3286 disappeared
2023-09-02 20:06:14,820 ERROR   StreamThr :3390 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-02 20:06:14,941 INFO    WriterThread:3390 [datastore.py:close():298] close: /root/autodl-tmp/msc_ml/llm_thought/Evaluation/wandb/run-20230902_200325-vwk90r2y/run-vwk90r2y.wandb
2023-09-02 20:06:14,945 INFO    HandlerThread:3390 [handler.py:finish():845] shutting down handler
2023-09-02 20:06:21,642 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:06:21,642 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:06:21,643 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:06:39,767 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:06:39,767 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:06:39,767 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:07:16,043 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:07:16,043 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:07:16,043 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:08:32,044 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:08:32,044 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:08:32,044 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:08:34,806 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:08:34,806 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:08:34,806 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:11:07,733 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:11:07,733 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:11:07,733 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:12:51,767 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:12:51,767 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:12:51,767 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:15:33,410 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:15:33,410 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:15:33,410 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:18:26,096 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:18:26,097 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:18:26,097 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:21:14,841 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:21:14,841 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:21:14,841 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:24:11,785 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:24:11,785 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:24:11,785 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:26:54,262 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:26:54,262 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:26:54,262 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:29:27,249 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:29:27,249 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:29:27,249 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:32:08,327 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:32:08,328 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:32:08,328 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:35:33,807 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:35:33,808 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:35:33,808 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:37:50,103 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:37:50,103 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:37:50,103 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:40:46,627 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:40:46,628 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:40:46,628 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:42:54,105 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:42:54,106 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:42:54,106 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:46:41,827 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:46:41,827 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:46:41,827 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:48:07,891 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:48:07,891 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:48:07,891 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:52:43,615 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:52:43,616 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:52:43,616 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:53:33,164 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:53:33,165 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:53:33,165 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:58:36,126 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:58:36,127 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 20:58:36,127 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 20:59:44,099 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 20:59:44,099 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 20:59:44,099 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:04:18,385 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:04:18,386 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:04:18,386 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:05:02,775 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:05:02,776 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:05:02,776 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:10:27,464 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:10:27,464 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:10:27,464 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:10:50,594 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:10:50,594 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:10:50,594 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:15:53,303 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:15:53,303 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:15:53,303 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:16:15,250 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:16:15,251 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:16:15,251 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:21:10,545 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:21:10,546 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:21:10,546 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:21:56,553 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:21:56,553 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:21:56,553 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:26:29,031 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:26:29,032 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:26:29,032 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:27:33,319 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:27:33,319 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:27:33,319 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:31:36,383 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:31:36,383 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:31:36,383 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:33:28,870 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:33:28,870 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:33:28,871 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:37:12,898 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:37:12,898 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:37:12,898 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:39:36,665 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:39:36,666 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:39:36,666 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:42:19,008 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:42:19,008 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:42:19,008 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:45:06,302 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:45:06,302 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:45:06,302 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:47:48,107 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:47:48,107 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:47:48,107 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:50:34,380 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:50:34,380 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:50:34,380 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:53:36,833 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:53:36,833 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:53:36,833 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:56:18,416 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ucl_2023_com00087/trlx/vwk90r2y/wandb-metadata.json?Expires=1693742611&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T0sevWALtZTOejxaczThx5F%2FD%2BGiGv4AwoLBeLBoqOcLcSBMzNvZrKMNyJ5yvdx2MqUhpCAWzg%2Bml5MfEQR9xSQiMv8b5erNguIXx9c6DV5LoQsNH%2F74LyU7nmwPcRqE53Xr9cFXenPyCbzKi0ojc28U5A%2Bn6JSp4ugASIl7sZtQzMekibGq076WXWmo8nYrK4FzyjoFNqNh7bxNIgQQiXz5K8eBH4pNsSJhOa%2F8qMVykTW5gJBSKkxdySOiPcJ8YdtWKkZlMM77nAzNWmmyXdTGzjDK%2B3vM46A%2BcKZhmxkLZbVeZaUpDbvD2eTMqxOaO0bhtVEdsyvWE4gvGzy%2FVQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:56:18,416 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9453'}
2023-09-02 21:56:18,416 ERROR   wandb-upload_0:3390 [internal_api.py:upload_file():2103] upload_file response body: 
2023-09-02 21:59:16,464 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/94466346/557603218/e90691de0f334b62cf2d8f7f82eceb55?Expires=1693742763&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgefgUGrpWBZGmrpJ9I9ZJyBoss4YrX0zRaqsFK%2BJXlyu6IWRA41vvIjTKMU5%2FhHkU1camNh181hOln3jfAnQGrwSU0XZaTHz3jPlOohQgbxZaZczEOg5Od5m6pgrrTDLWLgx3ttIw0fbYkh%2BNCSLkt1B45EgSfHhN0%2BEdtqZ2gr5yGypa%2FH5rY3sLg8U%2BcH1%2BTCUe9IDXypofzUWOM3PJudfJlO7vgR4hLUpOiWcoDXBapRqRBbdYia%2BScw8ak0W3mcn80DYJ8YUuNSSytRmBrze7L9IATk9ISJ7Okt%2Fqp%2Fm1mRSdaSIJsghMEOvy8%2FIfDsU%2FA3VZZkkqv4vJzQJw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-09-02 21:59:16,464 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '6QaR3g8zS2LPLY9/guzrVQ==', 'Content-Type': 'application/json', 'Content-Length': '13956'}
2023-09-02 21:59:16,464 ERROR   wandb-upload_2:3390 [internal_api.py:upload_file():2103] upload_file response body: 
